### ISSUE TITLE
"node ./bin/www" fails

### ISSUE THREAD

**Issue by eostermueller** [maxsivanov/influxdb-timeshift-proxy#1]
Hi,
This looks like a real helpful project, but I'm new to nodejs and am having trouble starting the server.
From the log:
```
23 error Tell the author that this fails on your system:
23 error     node ./bin/www

```
Attached is the full log.
Thanks,
--Erik

**Comment by maxsivanov** [comment]
Hi! I do not see any attachment.

**Comment by eostermueller** [comment]
Here are the contents of the log file:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'start' ]
2 info using npm@3.10.10
3 info using node@v6.10.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle influxdb-timeshift-proxy@0.0.3~prestart: influxdb-timeshift-proxy@0.0.3
6 silly lifecycle influxdb-timeshift-proxy@0.0.3~prestart: no script for prestart, continuing
7 info lifecycle influxdb-timeshift-proxy@0.0.3~start: influxdb-timeshift-proxy@0.0.3
8 verbose lifecycle influxdb-timeshift-proxy@0.0.3~start: unsafe-perm in lifecycle true
9 verbose lifecycle influxdb-timeshift-proxy@0.0.3~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/usr/app/influxdbTimeshiftProxy/influxdb-timeshift-proxy-master/node_modules/.bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/var/cfengine/bin:/home/app/bin
10 verbose lifecycle influxdb-timeshift-proxy@0.0.3~start: CWD: /usr/app/influxdbTimeshiftProxy/influxdb-timeshift-proxy-master
11 silly lifecycle influxdb-timeshift-proxy@0.0.3~start: Args: [ '-c', 'node ./bin/www' ]
12 silly lifecycle influxdb-timeshift-proxy@0.0.3~start: Returned: code: 1  signal: null
13 info lifecycle influxdb-timeshift-proxy@0.0.3~start: Failed to exec start script
14 verbose stack Error: influxdb-timeshift-proxy@0.0.3 start: `node ./bin/www`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:886:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid influxdb-timeshift-proxy@0.0.3
16 verbose cwd /usr/app/influxdbTimeshiftProxy/influxdb-timeshift-proxy-master
17 error Linux 2.6.32-696.1.1.el6.x86_64
18 error argv "/usr/bin/node" "/usr/bin/npm" "run" "start"
19 error node v6.10.3
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error influxdb-timeshift-proxy@0.0.3 start: `node ./bin/www`
22 error Exit status 1
23 error Failed at the influxdb-timeshift-proxy@0.0.3 start script 'node ./bin/www'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the influxdb-timeshift-proxy package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node ./bin/www
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs influxdb-timeshift-proxy
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls influxdb-timeshift-proxy
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by eostermueller** [comment]
It turns out my "npm i" didn't work because I didn't configure my proxy correctly, all good for now.

**Comment by pmagos00** [comment]
Hi Folks, i have the same issue, whith fedora core 

This is the output:

[root@localhost bin]# npm run start --debug

> influxdb-timeshift-proxy@0.0.4 start /herramientas/influxdb-timeshift-proxy
> node ./bin/www

Usage: INFLUXDB=127.0.0.1:8086 npm run start

npm ERR! Linux 4.8.6-300.fc25.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "start" "--debug"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! influxdb-timeshift-proxy@0.0.4 start: `node ./bin/www`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the influxdb-timeshift-proxy@0.0.4 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the influxdb-timeshift-proxy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs influxdb-timeshift-proxy
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls influxdb-timeshift-proxy
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /herramientas/influxdb-timeshift-proxy/bin/npm-debug.log
[root@localhost bin]# 

My npm i works

**Comment by pmagos00** [comment]
This is the output for npm-dedub.log

[root@localhost bin]# cat /herramientas/influxdb-timeshift-proxy/bin/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'start', '--debug' ]
2 info using npm@3.10.10
3 info using node@v6.10.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle influxdb-timeshift-proxy@0.0.4~prestart: influxdb-timeshift-proxy@0.0.4
6 silly lifecycle influxdb-timeshift-proxy@0.0.4~prestart: no script for prestart, continuing
7 info lifecycle influxdb-timeshift-proxy@0.0.4~start: influxdb-timeshift-proxy@0.0.4
8 verbose lifecycle influxdb-timeshift-proxy@0.0.4~start: unsafe-perm in lifecycle true
9 verbose lifecycle influxdb-timeshift-proxy@0.0.4~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/herramientas/influxdb-timeshift-proxy/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
10 verbose lifecycle influxdb-timeshift-proxy@0.0.4~start: CWD: /herramientas/influxdb-timeshift-proxy
11 silly lifecycle influxdb-timeshift-proxy@0.0.4~start: Args: [ '-c', 'node ./bin/www' ]
12 silly lifecycle influxdb-timeshift-proxy@0.0.4~start: Returned: code: 255  signal: null
13 info lifecycle influxdb-timeshift-proxy@0.0.4~start: Failed to exec start script
14 verbose stack Error: influxdb-timeshift-proxy@0.0.4 start: `node ./bin/www`
14 verbose stack Exit status 255
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:886:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid influxdb-timeshift-proxy@0.0.4
16 verbose cwd /herramientas/influxdb-timeshift-proxy/bin
17 error Linux 4.8.6-300.fc25.x86_64
18 error argv "/usr/bin/node" "/usr/bin/npm" "run" "start" "--debug"
19 error node v6.10.3
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error influxdb-timeshift-proxy@0.0.4 start: `node ./bin/www`
22 error Exit status 255
23 error Failed at the influxdb-timeshift-proxy@0.0.4 start script 'node ./bin/www'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the influxdb-timeshift-proxy package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node ./bin/www
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs influxdb-timeshift-proxy
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls influxdb-timeshift-proxy
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
[root@localhost bin]#

**Comment by eostermueller** [comment]
Did you check whether you had internet access?  That was my problem, and I fixed it by configuring the host name of my HTTP proxy.

**Comment by pmagos00** [comment]
Yes, i have access to internet. The output of npm i is correct.
