### ISSUE TITLE
[Q/A] Grafana 5.0

### ISSUE THREAD

**Issue by sanchomuzax** [maxsivanov/influxdb-timeshift-proxy#10]
Is the latest commit (71da48e  on Oct 28 2017) compatible with Grafana 5.0? 

Has anyone tried it yet?

I would like to upgrade to 5.0 beta, but I don't want to experiment with it. 😃 

Thank you!

**Comment by maxsivanov** [comment]
Not yet.

**Comment by sanchomuzax** [comment]
I tested it with beta3 and works fine. 😄

**Comment by maxsivanov** [comment]
Awesome!
