### ISSUE TITLE
cert error when using a private ca

### ISSUE THREAD

**Issue by pol** [maxsivanov/influxdb-timeshift-proxy#12]
Using a private ca, and ssl influxdb.  Get this error:

```
Error: unable to verify the first certificate
    at TLSSocket.&lt;anonymous&gt; (_tls_wrap.js:1105:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:639:8)
* Connection #0 to host localhost left intact
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:469:38)
```

I am going to dig around and see if I can suppress cert validation.

As a note, I am using the fqdn in the env var, but it still shows up as `localhost` in the error.  So even if it did have the ca pem, it would fail to validate (since the cert is for the fqdn).

**Comment by Codelica** [comment]
Check out the NODE_EXTRA_CA_CERTS env variable for Node.  As for the hostname, that works fine for me.  I'm sending in the INFLUXDB env variable via a PM2 startup config.  It is a full URI like "https://somehost.domain.com:8086"

**Comment by pol** [comment]
It's not ideal, but adding this to the systemd unit fixed it: `Environment=NODE_TLS_REJECT_UNAUTHORIZED=0`

That's what I am doing in other situations where I need to connect TLS to localhost, so it's not unusual (I have to do the same thing with the `influx` cli).
