### ISSUE TITLE
Unable to start influxdb-timeshift-proxy

### ISSUE THREAD

**Issue by SindhujaSoundarapandian** [maxsivanov/influxdb-timeshift-proxy#16]
Hi,

I have followed the steps to install influxdb timeshift proxy in my local machine and facing the below issue,

1.Downloaded zip file of influxdb-timeshift proxy and installed node.js 8.1 version
2.tried with the following command

>>npm i influxdb-timeshift-proxy -g
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated constantinople@3.0.2: Please update to at least constantinople 3.1.1
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
C:\Users\sindhuja.soundar\AppData\Roaming\npm\influxdb-timeshift-proxy -> C:\Users\sindhuja.soundar\AppData\Roaming\npm\node_modules\influxdb-timeshift-proxy\bin\www
+ influxdb-timeshift-proxy@0.0.8
updated 1 package in 2.064s
>>E:\influxdb-timeshift-proxy-master>influxdb=localhost:8086 npm run start
'influxdb' is not recognized as an internal or external command,
operable program or batch file.

Any help is much appreciated.

Thanks,

**Comment by ashishkaransingh** [comment]
Using npm@6.4.1
I have Influxdb installed. But cannot start it.
Getting the same error.

C:\Users\********\influxdb-timeshift-proxy>INFLUXDB=localhost:8086 influxdb-timeshift-proxy
'INFLUXDB' is not recognized as an internal or external command,
operable program or batch file.

**Comment by maxsivanov** [comment]
This is platform specific issue on Window. I do not have Windows near but the idea is to run proxy as follows
```
setx INFLUXDB localhost:8086
influxdb-timeshift-proxy
```
Write in this ticket if it does help

**Comment by ashishkaransingh** [comment]
Thanks!
After setting the env variable, I passed the command: "npm run start" and got below response printed.

influxdb-timeshift-proxy@0.0.8 start C:\Users\********\influxdb-timeshift-proxy
> node ./bin/www

**Comment by ashishkaransingh** [comment]
Able to start, i think this can be closed.

**Comment by ashishkaransingh** [comment]
I have a general question about the data proxy is fetching.
Should i open a new issue for it?

**Comment by maxsivanov** [comment]
New issue is better
