### ISSUE TITLE
a question

### ISSUE THREAD

**Issue by eostermueller** [maxsivanov/influxdb-timeshift-proxy#2]
Hello,

Say we run four different 1-hour tests over the course of a week, collecting data using this:
http://jmeter.apache.org/usermanual/realtime-results.html#influxdb

...and we'd like to see response time from all four tests compared to each other on a single graph, kind like this:

https://github.com/grafana/grafana/issues/171#issuecomment-113533494

Could you suggest what kind of query we'd use, perhaps with your "shift_x_seconds" syntax?

Thanks for this interesting project,

--Erik

**Comment by maxsivanov** [comment]
Hi!
You need multiple metrics to be added in graphana graph
First like that
SELECT non_negative_derivative("value", 1h) FROM "CPU_LOAD" WHERE "tag" = 'all' 
The second like that 
SELECT non_negative_derivative("value", 1h) AS "shift_360_seconds" FROM "CPU_LOAD" WHERE "tag" = 'all' 
The third like 
SELECT non_negative_derivative("value", 1h) AS "shift_720_seconds" FROM "CPU_LOAD" WHERE "tag" = 'all' 
And so on

**Comment by eostermueller** [comment]
perfect, thanks.
--Erik

**Comment by D3Hunter** [comment]
so how did you do it. @eostermueller 
@maxsivanov 's sqls are same except the `as` part, it's just a rename
