### ISSUE TITLE
Potentially clear other series (not just values) for Singlestat panel ?

### ISSUE THREAD

**Issue by Codelica** [maxsivanov/influxdb-timeshift-proxy#3]
Nice work here, very useful! :)

Just curious if you might consider an option to clear actual series output from the results (rather than just the values) so that it could (potentially) be used with the Singlestat panel? (which seems to require a single series returned)  

I'm basically trying to use your math function to just return the difference between a sum for this week and last week.  When turning on debugging for math I see:

```
  math Do math: $0 - $1 for statement: 2 +45s
  math 1495951200000 [ 20321.52, 16262.499999999996 ] 4059.020000000004 +0ms
  math Clear values for statement: 0 +0ms
  math Clear values for statement: 1 +0ms
``` 

Which looks good for the stat I'm after (4059.02), and I see "values" are cleared for the two series used to calculate it, but in Grafana I get a "Multiple Series Error" with the following returned:

> Metric query returns 3 series. Single Stat Panel expects a single series.
> 
> Response:
> [{"datapoints":[],"label":"POS_Financial.sum","id":"POS_Financial.sum","alias":"POS_Financial.sum","stats":{"total":0,"max":null,"min":null,"logmin":1.7976931348623157e+308,"avg":null,"current":null,"first":null,"delta":0,"diff":null,"range":null,"timeStep":1.7976931348623157e+308,"count":0},"legend":true,"hasMsResolution":false,"allIsNull":true,"allIsZero":true,"flotpairs":[]},{"datapoints":[],"label":"POS_Financial.shift_1_weeks","id":"POS_Financial.shift_1_weeks","alias":"POS_Financial.shift_1_weeks","stats":{"total":0,"max":null,"min":null,"logmin":1.7976931348623157e+308,"avg":null,"current":null,"first":null,"delta":0,"diff":null,"range":null,"timeStep":1.7976931348623157e+308,"count":0},"legend":true,"hasMsResolution":false,"allIsNull":true,"allIsZero":true,"flotpairs":[]},{"datapoints":[[4090.070000000007,1495951200000]],"label":"Difference","id":"Difference","alias":"Difference","stats":{"total":4090.070000000007,"max":4090.070000000007,"min":4090.070000000007,"logmin":4090.070000000007,"avg":4090.070000000007,"current":4090.070000000007,"first":4090.070000000007,"delta":0,"diff":0,"range":0,"timeStep":1.7976931348623157e+308,"count":1},"legend":true,"hasMsResolution":false,"allIsNull":false,"allIsZero":false,"flotpairs":[[1495951200000,4090.070000000007]]}]**

Just thinking if there were an option to exclude the full series from output, it **might** actually work :)

**UPDATE:**  FWIW the Singlestat panel does work fine when the other series are completely removed and only one is returned. 👍   To test things I just put:

```js
json.results = json.results.filter(result => result.series[0].values.length);
```

After the `math.vars.forEach()` loop at the end of the intercept() method.  I'm not familiar enough with Influx/Grafana to know wether there is a reason to return series w/ empty value arrays vs. removing the series completely.  But if you're open to the option, it would allow time shifted math with Singlestat panels.

**Comment by maxsivanov** [comment]
I'll take a look on singlestat panel for possible solutions.

**Comment by maxsivanov** [comment]
I've added singlestat option. It can be used instead of keep. See README.md
