### ISSUE TITLE
A few items related to query time ranges

### ISSUE THREAD

**Issue by Codelica** [maxsivanov/influxdb-timeshift-proxy#5]
Hello,

I just have a few small items related to query time ranges, so I'll put them all in this one issue.  I hope you don't feel I'm bugging you with these reports, I really appreciate the work you've done here! 👍 

1. At the top of handlers.js, the regular expressions for `from_rel` and `to_rel` are missing some possible time shorthands that both Grafana and Moment.js accept.   Currently it has:

```js
const from_rel = /(time > )(now\(\) - )([0-9]+)([hd])/;
const to_rel = /(time < )(now\(\) - )([0-9]+)([hd])/;
```

Which can be expanded to cover all supported cases:

```js
const from_rel = /(time > )(now\(\) - )([0-9]+)([smhdwMy])/;
const to_rel = /(time < )(now\(\) - )([0-9]+)([smhdwMy])/;
```

2. In handlers.js, on line 125 I think thing the wrong `fix_query_time` method is being called.  Currently it has:

```js
select = fix_query_time(select, to_rel, parseInt(match[1], 10), match[2]);
```

Which should be:

```js
select = fix_query_time_relative(select, to_rel, parseInt(match[1], 10), match[2]);
```

3.  And finally, I think there is an edge case for handling Grafana's "...so far" time ranges.   Basically when you pick a range like "This week so far", it will construct a query with a time range like:

```
... AND time > 1496296800000ms
```

Which doesn't have any time `to` condition to match and shift.  So for something like a query using "This week so far" and `shift_1_weeks`, it can actually return data that's time shifted into the future.  While it doesn't show up on graphs, it does show up when doing any "total" calculations in Grafana legends or SingleStat panels.  (And depending on the query, can just be a lot of extra data :) )

So it seems there needs to be a condition for when a query is supposed to be time shifted, and there isn't any time `to` condition, where one would be injected like `now() - <timeshift_duration>ms`.   Hope that makes sense?

Thanks again... 

**Edit:** Adding one other unrelated note, just because it's bit me a few times. :) If you're open to it, it would be nice for the regex on the timeshift alias to be case insensitive.  Currently it only picks up `AS` which Grafana supplies, but can get missed with manually written queries.   I just put in `[Aa][Ss]`

**Comment by maxsivanov** [comment]
Take a look on v0.0.7 seems like all issues are fixed.
