### ISSUE TITLE
Start error

### ISSUE THREAD

**Issue by navyaijm2017** [maxsivanov/influxdb-timeshift-proxy#6]
Hello, I am in accordance with the document installed error, help us to see what is the reason for it

[root@ip-10-10-111-111 influxdb-timeshift-proxy]# INFLUXDB=127.0.0.1:8088 npm run start 

> influxdb-timeshift-proxy@0.0.4 start /data/influxdb-timeshift-proxy
> node ./bin/www

/data/influxdb-timeshift-proxy/handlers.js:55
        const func = new Function(...math.vars, "return " + math.expr);
                                  ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/data/influxdb-timeshift-proxy/app.js:23:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

npm ERR! Linux 4.4.30-32.54.amzn1.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "start"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! influxdb-timeshift-proxy@0.0.4 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the influxdb-timeshift-proxy@0.0.4 start script 'node ./bin/www'.
npm ERR! This is most likely a problem with the influxdb-timeshift-proxy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs influxdb-timeshift-proxy
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls influxdb-timeshift-proxy
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /data/influxdb-timeshift-proxy/npm-debug.log

**Comment by maxsivanov** [comment]
Node.js 6 and later is required.
```npm ERR! node v4.5.0```
