### ISSUE TITLE
The real timeshift doesn't show up on graph

### ISSUE THREAD

**Issue by sanchomuzax** [maxsivanov/influxdb-timeshift-proxy#8]
I would like to show a graph of the current daily and one week ago data. What kind of graph setting is required for this? I can not set it up.

A:
`SELECT "value" FROM "a" WHERE $timeFilter`

B:
`SELECT "value" AS "shift_1_weeks" FROM "b" WHERE $timeFilter`

I can't see the "B" on the graph, only if change the "Time range" to "8d", and then "B" appears, but only on the last day.

![2017-10-25 22-10-05](https://user-images.githubusercontent.com/2911588/32022461-c02eb9d8-b9d6-11e7-876c-9782b9916a2a.png)

I would like to see the yellow "B" on this "1 day" view with the green "A". How?

![2017-10-25 22-10-28](https://user-images.githubusercontent.com/2911588/32022460-c00e11a6-b9d6-11e7-8b68-08537f4d94ac.png)

Thank you for your help!

**Comment by maxsivanov** [comment]
Probably database does not have enough data for previous week?

**Comment by sanchomuzax** [comment]
There is enough data since 09/14.

**Comment by sanchomuzax** [comment]
![2017-10-25 23-10-49](https://user-images.githubusercontent.com/2911588/32023423-7eeb1a40-b9d9-11e7-9328-f526f532b2bd.png)

**Comment by sanchomuzax** [comment]
The last 30 days with `shift_1_weeks` on the yellow line:

![2017-10-25 23-10-21](https://user-images.githubusercontent.com/2911588/32023780-a2a3a96a-b9da-11e7-8e20-da59f07f392d.png)

And last 7 days with `shift_1_weeks` on the yellow line:

![2017-10-25 23-10-52](https://user-images.githubusercontent.com/2911588/32023796-a9eb4412-b9da-11e7-9d63-719a29613372.png)

**Comment by Codelica** [comment]
Hard to know if this is what you are running into, but Grafana changed the way it forms time ranges for some queries starting with 4.5 I believe.  Basically they added an inclusive "=" to some output, which may not be getting picked up by the from* and to* regex in this project.  @maxsivanov if you want to take a peek at this, it may help.  https://github.com/Codelica/influxdb-timeshift-proxy/commit/d9c03d6161e46756ae44c432a007d486ef95d906

**Comment by maxsivanov** [comment]
I do not have latest grafana near but will try to merge that changes tomorrow.

**Comment by sanchomuzax** [comment]
Ah! I found the correct syntax for the `$timeFilter`:

```
SELECT non_negative_derivative(mean("value"), 1h) AS "shift_7_days" FROM "b" WHERE $timeFilter -7d GROUP BY time(60m) fill(null)
```

Usage the `"shift_7_days"` with the `$timeFilter -7d` formula.

![2017-10-27 23-10-43](https://user-images.githubusercontent.com/2911588/32126142-7a81d09c-bb6f-11e7-80a3-4d65a01a1d53.png)

and with the "Time range" function also:

![2017-10-27 23-10-38](https://user-images.githubusercontent.com/2911588/32126155-8ba6bd6a-bb6f-11e7-8343-b8c0c7ac9047.png)

👍 😃 

(tested with Grafana 4.6)

**Comment by maxsivanov** [comment]
I've changed regexp to be tolerant to spaces and inclusive compares. Looks like it's solved.

**Comment by sanchomuzax** [comment]
The best! 😄 The original formula works. There is no need for what I wrote the other day.

One more thing: Do not know if this phenomenon can be eliminated?

The value of the time shifted "Total" is 2 weeks if I set minus 1 week to it. Example: If the "A" has total value is 1000 in this week and previous week also, and I timeshift the "A" to "B", after the "B" has "Total" value is 2000.

**Comment by Codelica** [comment]
I'm pretty sure you are running into item 3 on issue #5.

Lines 129-134 on this commit has a fix I'm using.  https://github.com/Codelica/influxdb-timeshift-proxy/commit/9187272fb7dda3fdbbc590a22ff3bc60823afbfa
