### ISSUE TITLE
Usage of Singlestat panel - HOW?

### ISSUE THREAD

**Issue by sanchomuzax** [maxsivanov/influxdb-timeshift-proxy#9]
How could I use Singlestat panel with timeshift proxy?

This hasn't support multiple-series. But the essence of timeshift proxy feature is the multi-element operations.

![20171107161130](https://user-images.githubusercontent.com/2911588/32501228-c5d41670-c3d7-11e7-99d6-add70d724ea4.png)

**Comment by Codelica** [comment]
This is probably the same thing I ran into when trying to do math on singlestat aggregate quantities.  Basically the "time" to be matched up is different between the queries, so the math fails.  Not sure this is the best solution, or that it fixes all possibilities, but I made a workaround a while back as part of this commit, which I am using:

https://github.com/Codelica/influxdb-timeshift-proxy/commit/9187272fb7dda3fdbbc590a22ff3bc60823afbfa

**Comment by sanchomuzax** [comment]
Thank you! I'm going to try your repo.

Edit: I tried, but your version is not working. I don't want to report to it, because this is an other repo. But I can't add issue for yours.
